Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false 
Style/ClassVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8 #6
Metrics/MethodLength:
  Max: 14 #10
Metrics/ClassLength:
  Max: 280 #100
